"""Protocol and algorithm constants for reproducible rolling experiments."""

# These identifiers are written to every formal-format artifact.  Change them
# whenever the mathematical protocol, core algorithm, or output schema changes.
PROBLEM_PROTOCOL = "rolling-v4.3-oracle-certified-development"
ALGORITHM_VERSION = "lead-aware-aggregate-lp-screened-repair-v1.3"
RESULT_SCHEMA_VERSION = "rolling-results-v5"
FORMAL_CORE_CONFIGURATION = "full_bottleneck"
EXTERNAL_BASELINE_PROTOCOL = "adapted-literature-baselines-v1"
PREPROCESSING_IMPLEMENTATION = "lead-aware-aggregate-lp-sparse-indexed-v3"
PACKING_ORACLE_PROTOCOL = "full-horizon-integer-packing-v1"

# Development and preflight seeds may guide algorithm changes.  Formal seeds
# are a held-out set and must not be used for tuning before the final freeze.
DEVELOPMENT_SEEDS = (100, 101, 102)
PREFLIGHT_SEEDS = (700, 701, 702)
FORMAL_SEEDS = (1000, 1001, 1002, 1003, 1004)
ROLLING_CYCLE_HOURS=24
RECEIVING_WINDOW_HOURS=72
TIME_BUCKET_HOURS=6
LOOKAHEAD_HOURS=96
ADMISSION_LEAD_BAND_HOURS=(72,96)
DEFAULT_IMPACT_THRESHOLD=.10
DEFAULT_OUTBOUND_BOXES_PER_6H=150
INITIAL_BAY_MAX_FILL_RATIO=.95
INITIAL_UTILIZATION_TOLERANCE=1e-9
FORECAST_ERROR_MODES=(
    "multiplicative",
    "timing_shift",
    "booking_add_cancel",
    "ship_correlated",
    "mixed",
)
FORECAST_ERROR_CORRELATION=.70
FORECAST_MIN_SIGMA_RATIO=.05
SHIP_OPERATION_DURATION_RANGES={
    "small":(1,2),
    "medium":(2,3),
    "large":(3,4),
}
WALL_TIME_TOLERANCE_SECONDS=.20
POSTPROCESSING_RESERVE_RATIO=.15
POSTPROCESSING_RESERVE_MIN_SECONDS=.50
POSTPROCESSING_RESERVE_MAX_SECONDS=10.0
VALIDATE_EACH_EXECUTION_PERIOD=True
USE_EXACT_STABILITY_BIG_M=False

STABILITY_CANCEL_WEIGHT=1.0
STABILITY_NEW_BAY_WEIGHT=10.0
STABILITY_BLOCK_REALLOCATION_WEIGHT=1.0
STABILITY_BASE_RATIO=.10
STABILITY_CHANGE_RATIO=.50

OPERATION_OBJECTIVE_NORMALIZATION = "unrestricted_snapshot_scales"
OPERATION_WEIGHT_CONCENTRATION=1.0
OPERATION_WEIGHT_BALANCE=1.0
OPERATION_WEIGHT_DISTANCE=1.0
OPERATION_WEIGHT_IN_OUT_CONFLICT=1.0

ADAPTIVE_BLOCK_BATCH_RATIO=.20
ADAPTIVE_GLOBAL_BYPASS_ENABLED=True
# Bypass the restricted repair path only when both a horizon-wide load measure
# and a current free-capacity measure indicate severe pressure.  These tests use
# snapshot state rather than instance-size labels.
ADAPTIVE_GLOBAL_PEAK_LOAD_THRESHOLD=.80
ADAPTIVE_GLOBAL_DEMAND_FREE_CAPACITY_THRESHOLD=1.0
AGGREGATE_DOMAIN_LADDER_ENABLED=True
AGGREGATE_DOMAIN_LADDER_BUDGET_RATIO=.05
AGGREGATE_DOMAIN_LADDER_MAX_SECONDS=1.0
AGGREGATE_DOMAIN_LADDER_LEVELS=(0,1,2)
# The declared forecast-error magnitude is combined with the maximum visible
# lead-time sigma and used as a conservative screening buffer. It is not
# presented as a probabilistic confidence radius.
AGGREGATE_DOMAIN_LADDER_BUFFER_MULTIPLIER=1.0
BOTTLENECK_SELECTOR_BUDGET_RATIO=.05
BOTTLENECK_SELECTOR_MAX_SECONDS=1.0
QUALITY_POLISH_ENABLED=False
QUALITY_POLISH_PAIR_RATIO=.50
QUALITY_POLISH_BLOCKS_PER_PAIR=2
QUALITY_POLISH_WEIGHT_SUPPORT=1.0
QUALITY_POLISH_WEIGHT_DISTANCE=1.0
QUALITY_POLISH_WEIGHT_OVERLAP=1.0
QUALITY_POLISH_WEIGHT_UTILIZATION=1.0
IMPACT_SCORE_CAPACITY_WEIGHT=5.0
IMPACT_SCORE_DISTANCE_WEIGHT=1.25
IMPACT_SCORE_OUTBOUND_WEIGHT=1.25
IMPACT_SCORE_BALANCE_WEIGHT=1.0
IMPACT_SCORE_BAY_WEIGHT=.75
IMPACT_SCORE_STABILITY_WEIGHT=2.0
TIME_CAPACITY_WEIGHT=.70
MINIMUM_PERIOD_CAPACITY_WEIGHT=.30

DEPENDENCY_PROPAGATION_ENABLED=True
DEPENDENCY_TRIGGER_MODE="shortage_repair_only"
DEPENDENCY_CANDIDATE_BLOCK_RATIO=.30
DEPENDENCY_EDGE_THRESHOLD=.35
DEPENDENCY_PATH_THRESHOLD=.20
DEPENDENCY_PROFILES={
    "conservative":{"edge_threshold":.50,"path_threshold":.35},
    "current":{"edge_threshold":DEPENDENCY_EDGE_THRESHOLD,"path_threshold":DEPENDENCY_PATH_THRESHOLD},
    "expansive":{"edge_threshold":.20,"path_threshold":.10},
}
DEPENDENCY_MAX_DEPTH=2
DEPENDENCY_DECAY=.85
DEPENDENCY_MAX_NEIGHBORS_PER_PAIR=8
DEPENDENCY_WEIGHT_CANDIDATE_OVERLAP=.35
DEPENDENCY_WEIGHT_TEMPORAL_OVERLAP=.25
DEPENDENCY_WEIGHT_CAPACITY_PRESSURE=.25
DEPENDENCY_WEIGHT_HISTORICAL_OVERLAP=.15
