from __future__ import annotations
import argparse,csv,json,statistics,sys
from collections import defaultdict
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))

def get(row,path,default=None):
    value=row
    for key in path:
        if not isinstance(value,dict):return default
        value=value.get(key)
    return default if value is None else value
def stats(values):
    values=[float(v) for v in values if v is not None]
    return {"mean":statistics.mean(values) if values else None,"median":statistics.median(values) if values else None,"min":min(values) if values else None,"max":max(values) if values else None,"stddev":statistics.pstdev(values) if len(values)>1 else 0.0 if values else None}
def summarize(rows,key):
    groups=defaultdict(list)
    for row in rows:groups[key(row)].append(row)
    result=[]
    for name,items in sorted(groups.items(),key=lambda x:str(x[0])):
        ev=[r for r in items if r["status"]["ok"]];record={"group":name,"runs":len(items),"feasible_rate":len(ev)/len(items),"optimal_rate":sum(r["status"]["status"]=="OPTIMAL" for r in items)/len(items)}
        for label,path in {"ub":("optimization","ub"),"lb":("optimization","lb"),"gap":("optimization","gap"),"runtime":("timing","wall_clock"),"nodes":("optimization","nodes"),"root_initial_bound":("method_diagnostics","root","initial_bound"),"root_final_bound":("method_diagnostics","root","final_bound"),"root_improvement":("method_diagnostics","root","bound_improvement"),"root_runtime":("method_diagnostics","root","runtime"),"warm_initial_ub":("method_diagnostics","warm","initial_ub"),"warm_runtime":("method_diagnostics","warm","runtime"),"alns_start_ub":("method_diagnostics","alns","start_ub"),"alns_best_ub":("method_diagnostics","alns","best_ub"),"alns_improvement":("method_diagnostics","alns","improvement"),"alns_runtime":("method_diagnostics","alns","runtime"),"callback_time":("method_diagnostics","main","callback_time"),"open_hours":("evaluation","kpis","open_usage","open_bay_hours"),"concentration":("evaluation","kpis","concentration","joint_group_bay_usage_total"),"distance_per_box":("evaluation","kpis","distance","distance_per_arrival_box"),"workload_cv":("evaluation","kpis","workload","workload_cv_mean_active_periods"),"conflict_per_box":("evaluation","kpis","conflict","conflict_per_arrival_box"),"reserved_utilization":("evaluation","kpis","utilization","reserved","mean")}.items():record.update({f"{label}_{k}":v for k,v in stats([get(r,path) for r in items]).items()})
        result.append(record)
    return result
def write_csv(path,rows):
    if not rows:return
    with Path(path).open("w",newline="",encoding="utf-8") as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
def main():
    p=argparse.ArgumentParser();p.add_argument("--input",default="experiments/pilot_calibration/raw_results.jsonl");p.add_argument("--output",default="experiments/pilot_calibration");a=p.parse_args();rows=[json.loads(line) for line in Path(a.input).read_text(encoding="utf-8").splitlines() if line.strip()];out=Path(a.output);size_map={"S01":"small","M01":"medium","L01":"large"};by_instance=summarize(rows,lambda r:r["identity"]["instance_id"]);by_config=summarize(rows,lambda r:r["identity"]["configuration_name"]);by_size=summarize(rows,lambda r:size_map[r["identity"]["instance_id"]]);write_csv(out/"summary_by_instance.csv",by_instance);write_csv(out/"summary_by_configuration.csv",by_config);write_csv(out/"summary_by_size.csv",by_size)
    facts={r["group"]:r for r in by_size};difficulty=[]
    for size in ("small","medium","large"):
        f=facts[size];difficulty.append(f"- **{size.title()}**: feasible rate {f['feasible_rate']:.1%}, optimal-status rate {f['optimal_rate']:.1%}, median gap {f['gap_median'] if f['gap_median'] is not None else 'N/A'}, median runtime {f['runtime_median']:.2f}s.")
    kpi_names=("open_hours","concentration","distance_per_box","workload_cv","conflict_per_box","reserved_utilization");signals={name:stats([get(r,("evaluation","kpis",*({"open_hours":("open_usage","open_bay_hours"),"concentration":("concentration","joint_group_bay_usage_total"),"distance_per_box":("distance","distance_per_arrival_box"),"workload_cv":("workload","workload_cv_mean_active_periods"),"conflict_per_box":("conflict","conflict_per_arrival_box"),"reserved_utilization":("utilization","reserved","mean")}[name]))) for r in rows]) for name in kpi_names}
    degenerate=[name for name,value in signals.items() if value["min"] is not None and abs(value["max"]-value["min"])<1e-9]
    difficulty_md="# Pilot difficulty calibration\n\nThis is a development pilot, not a final paper result. The first screen uses S01/M01/L01 only, with 15/30/45 second budgets. S01 stochastic configurations use seeds 0/1/2; Medium and Large currently use seed 0 only.\n\n"+"\n".join(difficulty)+f"\n\nKPI signals with zero observed range: {', '.join(degenerate) or 'none'}.\n\n## Preliminary judgment\n\n- Small retains the exact-crosscheck role: the separate 600-second gate proved S01–S03 exact, while this short screen is mostly optimal.\n- Medium finds feasible solutions consistently and shows mixed optimality/gaps, so it can discriminate configurations in the next round.\n- Large is materially harder: no run reports optimal and some configurations find no incumbent, while most still return feasible solutions. It is usable for finite-time comparison but needs more instances/seeds before freezing its scale.\n- Pilot1 is retained without modification; no evidence yet requires `paper_exp_v1_pilot2`.\n\nFinal algorithm is not frozen in Task 10.\n";(out/"difficulty_report.md").write_text(difficulty_md,encoding="utf-8")
    config={r["group"]:r for r in by_config};core=config.get("bbc_core",{});recommendations=[]
    for name in ("bbc_valid","bbc_root","bbc_warm","bbc_alns","bbc_root_warm","bbc_root_alns","bbc_full_current"):
        item=config.get(name,{});delta=None if core.get("gap_median") is None or item.get("gap_median") is None else core["gap_median"]-item["gap_median"];category="Keep for next round" if delta is not None and delta>.01 else "Needs more evidence";recommendations.append({"configuration":name,"category":category,"median_gap_improvement_vs_core":delta,"runs":item.get("runs"),"note":"Pilot evidence only; confirm with more instances and seeds."})
    component_lines=["# Algorithm component pilot","","No component is frozen or deleted in this stage.",""]+[f"- **{r['configuration']}**: {r['category']}; median gap change vs core = {r['median_gap_improvement_vs_core']}." for r in recommendations]+["","## Collected component diagnostics",""]+[f"- **{name}**: root improvement median={config.get(name,{}).get('root_improvement_median')}, root time median={config.get(name,{}).get('root_runtime_median')}s, warm initial UB median={config.get(name,{}).get('warm_initial_ub_median')}, ALNS improvement median={config.get(name,{}).get('alns_improvement_median')}, ALNS time median={config.get(name,{}).get('alns_runtime_median')}s, nodes median={config.get(name,{}).get('nodes_median')}." for name in ("bbc_core","bbc_valid","bbc_root","bbc_warm","bbc_alns","bbc_root_warm","bbc_root_alns","bbc_full_current")]+["","Successful ALNS operator counts remain available per run in `method_diagnostics.alns.successful_operators` within `raw_results.jsonl`.","","Aggregate/analytic LB are jointly present in root/full configurations in this first progressive screen; separating their individual effects requires next-round ablation.","","Stabilized and node-cut configurations were not run because no prior evidence yet justified their callback cost.","","Final algorithm is not frozen in Task 10."];(out/"component_report.md").write_text("\n".join(component_lines)+"\n",encoding="utf-8");payload={"status":"pilot_only","final_algorithm_frozen":False,"selected_instances":["S01","M01","L01"],"seed_policy":"S01 stochastic configs use 0,1,2; M01/L01 preliminary seed 0 only","recommendations":recommendations,"benchmark_adjustment_needed":False,"benchmark_note":"Observed feasibility and KPI variation are assessed in difficulty_report.md; retain pilot1 pending broader calibration.","kpi_signal_stats":signals};(out/"recommendations.json").write_text(json.dumps(payload,indent=2,ensure_ascii=False)+"\n",encoding="utf-8");print(f"analyzed {len(rows)} runs; zero-range KPIs={degenerate}");return 0
if __name__=="__main__":raise SystemExit(main())
